"""
LLM-as-Judge metric for evaluating answer alignment in ask mode benchmarks.

Uses DSPy to create a structured LLM judge that assesses whether a system's
answer is semantically aligned with the expected/correct answer.
"""

import os
from typing import Optional

import dspy


class AssessAlignmentScore(dspy.Signature):
    """You are an expert grader assessing if a system's answer is semantically aligned with the correct answer.
    Only return True if the system answer has essentially the same meaning as the correct answer.
    If the system answer misses key aspects or meaning, return False.
    """

    question: str = dspy.InputField(description="The question asked.")
    system_answer: str = dspy.InputField(description="The answer generated by the system.")
    correct_answer: str = dspy.InputField(description="The reference answer containing the correct and complete information.")
    reasoning: str = dspy.OutputField(description="Step-by-step reasoning about whether the system answer is semantically aligned with the correct answer.")
    score: bool = dspy.OutputField(description="True if system_answer is equivalent in meaning to correct_answer, otherwise False.")


class LMJudge:
    """
    LLM-as-Judge for evaluating answer alignment.
    
    Uses ensemble voting for more robust evaluation - runs K independent
    judge predictions and returns True if majority vote is positive.
    
    Example:
        >>> judge = LMJudge(model="openai/gpt-4.1", ensemble_k=3)
        >>> score = judge.evaluate(
        ...     question="What is HyDE?",
        ...     system_answer="HyDE is a retrieval technique.",
        ...     correct_answer="HyDE stands for Hypothetical Document Embeddings..."
        ... )
        >>> print(score)  # True or False
    """
    
    def __init__(
        self,
        model: str = "openai/gpt-4.1",
        ensemble_k: int = 3,
        api_key: Optional[str] = None,
        cache: bool = False,
    ):
        """
        Initialize the LM Judge.
        
        Args:
            model: The LLM model to use (e.g., "openai/gpt-4.1", "anthropic/claude-3-opus").
            ensemble_k: Number of independent judge calls for ensemble voting.
            api_key: API key for the LLM provider. Defaults to OPENAI_API_KEY env var.
            cache: Whether to cache LLM responses. Disabled by default for evaluation.
        """
        self.model = model
        self.ensemble_k = ensemble_k
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.cache = cache
        
        # Initialize DSPy LM
        self.lm = dspy.LM(
            model,
            cache=cache,
            api_key=self.api_key
        )
        dspy.configure(lm=self.lm, track_usage=True)
        
        # Create the judge predictor
        self.judge = dspy.Predict(AssessAlignmentScore)
    
    def evaluate(
        self,
        question: str,
        system_answer: str,
        correct_answer: str,
    ) -> bool:
        """
        Evaluate if system_answer is semantically aligned with correct_answer.
        
        Uses ensemble voting: runs K independent predictions and returns True
        if the majority vote is positive.
        
        Args:
            question: The question that was asked.
            system_answer: The answer generated by the system being evaluated.
            correct_answer: The ground truth/expected answer.
            
        Returns:
            bool: True if answers are aligned (majority vote), False otherwise.
        """
        votes = 0
        
        for _ in range(self.ensemble_k):
            response = self.judge(
                question=question,
                system_answer=system_answer,
                correct_answer=correct_answer
            )
            if response.score:
                votes += 1
        
        # Majority voting
        return votes >= self.ensemble_k / 2
    
    def evaluate_with_details(
        self,
        question: str,
        system_answer: str,
        correct_answer: str,
    ) -> dict:
        """
        Evaluate with detailed results including vote count and token usage.

        Args:
            question: The question that was asked.
            system_answer: The answer generated by the system being evaluated.
            correct_answer: The ground truth/expected answer.

        Returns:
            dict: Contains 'aligned', 'votes', 'ensemble_k', 'reasoning', and token usage keys.
        """
        votes = 0
        total_input_tokens = 0
        total_output_tokens = 0
        responses = []

        for _ in range(self.ensemble_k):
            response = self.judge(
                question=question,
                system_answer=system_answer,
                correct_answer=correct_answer
            )
            responses.append(response)
            if response.score:
                votes += 1

            # Track token usage
            try:
                usage = response.get_lm_usage()
                if usage and self.model in usage:
                    total_input_tokens += usage[self.model].get("prompt_tokens", 0)
                    total_output_tokens += usage[self.model].get("completion_tokens", 0)
            except Exception:
                pass  # Token tracking is best-effort

        aligned = votes >= self.ensemble_k / 2

        # Find reasoning from a judge whose vote agrees with the majority outcome
        majority_reasoning = None
        for response in responses:
            if response.score == aligned:
                majority_reasoning = response.reasoning
                break

        return {
            "aligned": aligned,
            "votes": votes,
            "ensemble_k": self.ensemble_k,
            "input_tokens": total_input_tokens,
            "output_tokens": total_output_tokens,
            "reasoning": majority_reasoning,
        }


def calculate_alignment_score(
    question: str,
    system_answer: str,
    correct_answer: str,
    model: str = "openai/gpt-4.1",
    ensemble_k: int = 3,
) -> bool:
    """
    Convenience function to evaluate alignment without creating a judge instance.
    
    For batch evaluations, prefer creating an LMJudge instance once and reusing it.
    
    Args:
        question: The question that was asked.
        system_answer: The answer generated by the system.
        correct_answer: The ground truth answer.
        model: LLM model to use.
        ensemble_k: Number of ensemble votes.
        
    Returns:
        bool: True if answers are aligned, False otherwise.
    """
    judge = LMJudge(model=model, ensemble_k=ensemble_k)
    return judge.evaluate(question, system_answer, correct_answer)

