dataset_name: bright/biology

embedding_model: "weaviate/Snowflake/snowflake-arctic-embed-l-v2.0"

# MUVERA+HNSW parameters
use_MUVERA_encoding: False
ksim: 4
dprojections: 16
repetitions: 10
ef: 500
