dataset_name: irpapers/text

embedding_model: "voyageai/voyage-3-large"

# MUVERA+HNSW parameters (only used with weaviate provider)
use_MUVERA_encoding: False
ksim: 4
dprojections: 16
repetitions: 10
ef: 500
