dataset_name: irpapers

# NOTE: This is a work in progess, need a better abstraction for multiple models from the same provider.
# The problem is X_weaviate_snowflake_... ends up being really verbose when you need to
# reference it in the benchmark config.

# Use a list to create multiple provider-qualified text vectors, e.g.
# `text_content_weaviate`, `text_content_cohere`.
text_embedding_models:
  - "weaviate/Snowflake/snowflake-arctic-embed-l-v2.0"

image_embedding_model: "weaviate/ModernVBERT/colmodernvbert"

# MUVERA+HNSW parameters
use_MUVERA_encoding: False
ksim: 4
dprojections: 16
repetitions: 10
ef: 500
