"""
Exact match metric for evaluating answer accuracy in ask mode benchmarks.

Compares system answers to ground truth answers using exact string matching
(normalized for case and whitespace).
"""


def calculate_exact_match(
    system_answer: str,
    ground_truth_answer: str,
    case_sensitive: bool = False,
) -> bool:
    """
    Calculate exact match between system answer and ground truth.
    
    Args:
        system_answer: The answer generated by the system.
        ground_truth_answer: The expected/correct answer.
        case_sensitive: Whether to perform case-sensitive matching (default: False).
        
    Returns:
        bool: True if answers match exactly (after normalization), False otherwise.
    """
    # Normalize whitespace (strip and collapse multiple spaces)
    system_normalized = " ".join(system_answer.strip().split())
    ground_truth_normalized = " ".join(ground_truth_answer.strip().split())
    
    if not case_sensitive:
        system_normalized = system_normalized.lower()
        ground_truth_normalized = ground_truth_normalized.lower()
    
    return system_normalized == ground_truth_normalized
