"""Port interface for LLM-based answer evaluation."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMJudge(Protocol):
    """Protocol for LLM-based semantic alignment evaluation."""

    def evaluate(
        self,
        question: str,
        system_answer: str,
        correct_answer: str,
    ) -> bool:
        """Evaluate if system answer is semantically aligned with the correct answer.

        Args:
            question: The question that was asked.
            system_answer: The answer generated by the system.
            correct_answer: The ground truth answer.

        Returns:
            True if answers are aligned, False otherwise.
        """
        ...

    def evaluate_with_details(
        self,
        question: str,
        system_answer: str,
        correct_answer: str,
    ) -> dict:
        """Evaluate with detailed results including vote count and token usage.

        Args:
            question: The question that was asked.
            system_answer: The answer generated by the system.
            correct_answer: The ground truth answer.

        Returns:
            Dictionary with 'aligned', 'votes', 'ensemble_k', and token usage.
        """
        ...
