agent_name: query-agent-search-only
agents_host: http://localhost:8000
dataset: beir/scifact/test
use_async: True
use_subset: False
num_samples: 5
num_trials: 3
batch_size: 5
max_concurrent: 5
experiment_name: query-agent-search-only