agent_name: hybrid-search
agents_host: http://localhost:8000
dataset: wixqa
use_async: True
use_subset: False
num_samples: 500
num_trials: 1
batch_size: 5
max_concurrent: 5
experiment_name: hybrid-search