agent_name: hybrid-search
agents_host: http://localhost:8000
dataset: beir/nfcorpus/train
use_async: False
reload_database: False
num_samples: 20
batch_size: 5
max_concurrent: 5
experiment_name: hybrid-search