agent_name: query-agent-search-only
agents_host: http://localhost:8000
dataset: enron
use_async: True
reload_database: False
num_samples: 100
batch_size: 5
max_concurrent: 5
experiment_name: query-agent-search-only