agent_name: hybrid-search
agents_host: https://dev-agents.labs.weaviate.io
dataset: enron
use_async: True
reload_database: False
num_samples: 200
batch_size: 5
max_concurrent: 5
experiment_name: hybrid-search